const Sequelize = require('sequelize');

module.exports = {
    id:{
        type:Sequelize.STRING(36),
        primaryKey:true,
        allowNull:false,
        defaultValue:Sequelize.UUIDV1
    },
    orderId:{
        type:Sequelize.STRING(36),
        allowNull:false,
        references:{
            model:'order',
            key:'id'
        }
    },
    productId:{
        type:Sequelize.STRING(36),
        allowNull:false,
        references:{
            model:'product',
            key:'id'
        }
    },
    price:{
        type:Sequelize.DOUBLE
    },
    tax:{
        type:Sequelize.DOUBLE
    },
    discount:{
        type:Sequelize.DOUBLE
    },
    totalPrice:{
        type:Sequelize.DOUBLE
    },
    isDeleted:{
        type:Sequelize.BOOLEAN
    }
}